# Generated by Django 5.2.16 on 2026-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_stage',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer')], default='Lead', max_length=20),
        ),
    ]
