# Generated by Django 5.2.16 on 2026-08-19 20:02

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_admins(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    # Create Madhav Admin
    User.objects.filter(email='madhavpharmaindustries@gmail.com').delete()
    User.objects.create(
        email='madhavpharmaindustries@gmail.com',
        password=make_password('Madhav@0267'),
        role='Admin',
        first_name='Madhav Pharma',
        last_name='Admin',
        is_staff=True,
        is_superuser=True,
        is_verified=True,
        is_active=True
    )
    
    # Create Om Admin
    User.objects.filter(email='theom.chaudhari@gmail.com').delete()
    User.objects.create(
        email='theom.chaudhari@gmail.com',
        password=make_password('Omsc@990'),
        role='Admin',
        first_name='Om',
        last_name='Admin',
        is_staff=True,
        is_superuser=True,
        is_verified=True,
        is_active=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_customer_stage'),
    ]

    operations = [
        migrations.RunPython(create_admins, reverse_code=migrations.RunPython.noop),
    ]
