# Generated by Django 5.2.16 on 2026-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_sales_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprecord',
            name='otp',
        ),
        migrations.AddField(
            model_name='otprecord',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='purpose',
            field=models.CharField(default='registration', max_length=30),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
