# Generated by Django 5.2.16 on 2026-08-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_b2b_oos_product_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_images_5l',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='description_5l',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price_5l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
