# Generated by Django 5.2.16 on 2026-08-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='Razorpay', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Pending Verification', 'Pending Verification')], default='Pending', max_length=30),
        ),
    ]
