# Generated by Django 5.2.16 on 2026-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='snapshot_customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='snapshot_customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='snapshot_customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
